//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooptyDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string Matricule { get; set; }
        public string Nom { get; set; }
        public string Price { get; set; }
        public string Qte { get; set; }
        public int IdMarque { get; set; }
        public int IdCategorie { get; set; }
    }
}
