//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooptyDashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public string ShoppingCartId_ { get; set; }
        public string ShoppingCartItemId { get; set; }
    }
}
