//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooptyClient.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        //public int Id_Order_Detail { get; set; }
        //public Nullable<int> Id_Order { get; set; }
        //public Nullable<int> Id_Product { get; set; }
        //public string Name_Product { get; set; }
        //public Nullable<int> Qte { get; set; }
        //public Nullable<double> Price { get; set; }
        //public Nullable<double> Total_Money { get; set; }

        public int OrderDetailId { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public virtual Product Item { get; set; }
        public virtual Order Order { get; set; }
    }
}
